<?php
/**
 * Plugin Name: Display Auto-Generated URLs
 * Description: Finds and displays auto-generated URLs like author archives, 404, search, feeds, REST API, trackbacks, media, archives, and CPT archives.
 * Version: 1.2.1
 * Requires at least: 5.9
 * Author: Justin Thompson
 * Author URI: https://justy.dev
 * Text Domain: autogenerated-urls
 *
 * @package Autogenerated_URLs
 */

define( 'AGUD_TEXT_DOMAIN', 'autogenerated-urls' );
define( 'AGUD_ITEMS_PER_PAGE', 100 );
define( 'AGUD_PAGE_QUERY_ARG', 'agud_page' );

add_action(
	'plugins_loaded',
	function () {
		load_plugin_textdomain( AGUD_TEXT_DOMAIN, false, dirname( plugin_basename( __FILE__ ) ) . '/languages' );
	}
);

add_action(
	'admin_menu',
	function () {
		add_management_page(
			__( 'Auto-Generated URLs', 'autogenerated-urls' ),
			__( 'Auto URLs', 'autogenerated-urls' ),
			'manage_options',
			'auto-generated-urls',
			'agud_display_page'
		);
	}
);

add_filter( 'plugin_action_links_' . plugin_basename( __FILE__ ), 'agud_plugin_action_links' );

/**
 * Add a shortcut to the plugin's Tools page.
 *
 * @param array $links Existing plugin action links.
 * @return array Filtered plugin action links.
 */
function agud_plugin_action_links( array $links ): array {
	$view_urls_link = '<a href="' . esc_url( admin_url( 'tools.php?page=auto-generated-urls' ) ) . '">' . esc_html__( 'View URLs', 'autogenerated-urls' ) . '</a>';

	return array( 'agud-view-urls' => $view_urls_link ) + $links;
}

/**
 * Render the Auto-Generated URLs admin page.
 */
function agud_display_page(): void {
	$page = agud_get_current_page();

	echo '<div class="wrap"><h1>' . esc_html__( 'Auto-Generated URLs', 'autogenerated-urls' ) . '</h1>';

	foreach ( agud_get_page_sections( $page ) as $section ) {
		agud_section( $section['title'], $section['urls'], $section['total'], $section['page'] );
	}

	echo '</div>';
}

/**
 * Get the requested shared pagination page.
 *
 * @return int Current page, with a minimum value of one.
 */
function agud_get_current_page(): int {
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended, WordPress.Security.ValidatedSanitizedInput.MissingUnslash, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- This read-only pagination value is unslashed and validated below.
	$raw_page = $_GET[ AGUD_PAGE_QUERY_ARG ] ?? 1;
	$page     = is_scalar( $raw_page ) ? (int) sanitize_text_field( wp_unslash( (string) $raw_page ) ) : 1;

	return max( 1, $page );
}

/**
 * Collect the ordered section data for the admin page.
 *
 * @param int $page Current shared pagination page.
 * @return array Ordered section descriptors for the page renderer.
 */
function agud_get_page_sections( int $page ): array {
	$author_total     = 0;
	$attachment_total = 0;
	$category_total   = 0;
	$tag_total        = 0;

	$author_urls     = agud_get_author_urls( $page, $author_total );
	$attachment_urls = agud_get_attachment_urls( $page, $attachment_total );
	$category_urls   = agud_get_taxonomy_urls( 'category', $page, $category_total );
	$tag_urls        = agud_get_taxonomy_urls( 'post_tag', $page, $tag_total );

	return array(
		array(
			'title' => __( 'Author Archives', 'autogenerated-urls' ),
			'urls'  => $author_urls,
			'total' => $author_total,
			'page'  => $page,
		),
		array(
			'title' => __( 'Static Pages', 'autogenerated-urls' ),
			'urls'  => array(
				__( '404 Example', 'autogenerated-urls' ) => home_url( '/this-path-should-404/' ),
				__( 'Search Page', 'autogenerated-urls' ) => home_url( '/?s=' ),
			),
			'total' => 0,
			'page'  => 1,
		),
		array(
			'title' => __( 'Media Attachments', 'autogenerated-urls' ),
			'urls'  => $attachment_urls,
			'total' => $attachment_total,
			'page'  => $page,
		),
		array(
			'title' => __( 'Category Archives', 'autogenerated-urls' ),
			'urls'  => $category_urls,
			'total' => $category_total,
			'page'  => $page,
		),
		array(
			'title' => __( 'Tag Archives', 'autogenerated-urls' ),
			'urls'  => $tag_urls,
			'total' => $tag_total,
			'page'  => $page,
		),
		array(
			'title' => __( 'Date Archives', 'autogenerated-urls' ),
			'urls'  => agud_get_date_archive_urls(),
			'total' => 0,
			'page'  => 1,
		),
		array(
			'title' => __( 'Feed Endpoints', 'autogenerated-urls' ),
			'urls'  => array(
				__( 'Main Feed', 'autogenerated-urls' ) => home_url( '/feed/' ),
				__( 'Comments Feed', 'autogenerated-urls' ) => home_url( '/comments/feed/' ),
			),
			'total' => 0,
			'page'  => 1,
		),
		array(
			'title' => __( 'REST API', 'autogenerated-urls' ),
			'urls'  => array(
				__( 'REST API Root', 'autogenerated-urls' ) => rest_url(),
			),
			'total' => 0,
			'page'  => 1,
		),
		array(
			'title' => __( 'Pingback URL', 'autogenerated-urls' ),
			'urls'  => array(
				__( 'Pingback URL', 'autogenerated-urls' ) => get_bloginfo( 'pingback_url' ),
			),
			'total' => 0,
			'page'  => 1,
		),
		array(
			'title' => __( 'Custom Post Type Archives', 'autogenerated-urls' ),
			'urls'  => agud_get_cpt_archive_urls(),
			'total' => 0,
			'page'  => 1,
		),
		array(
			'title' => __( 'Sitemap', 'autogenerated-urls' ),
			'urls'  => array(
				__( 'XML Sitemap', 'autogenerated-urls' ) => home_url( '/wp-sitemap.xml' ),
			),
			'total' => 0,
			'page'  => 1,
		),
	);
}

/**
 * Render one URL section and its pagination controls.
 *
 * @param string $title Section heading.
 * @param array  $urls  Labels mapped to URLs.
 * @param int    $total Total items available.
 * @param int    $page  Current page.
 */
function agud_section( string $title, array $urls, int $total = 0, int $page = 1 ): void {
	echo '<h2>' . esc_html( $title ) . '</h2>';
	if ( empty( $urls ) ) {
		echo '<p>' . esc_html__( 'None found.', 'autogenerated-urls' ) . '</p>';
		return;
	}
	echo '<ul>';
	foreach ( $urls as $name => $url ) {
		if ( ! is_string( $url ) || '' === $url ) {
			continue;
		}
		echo '<li><strong>' . esc_html( $name ) . ':</strong> <a href="' . esc_url( $url ) . '" target="_blank" rel="noopener noreferrer">' . esc_html( $url ) . '</a></li>';
	}
	echo '</ul>';

	$page_count = (int) ceil( $total / AGUD_ITEMS_PER_PAGE );
	if ( $page_count > 1 ) {
		echo '<div class="tablenav"><div class="tablenav-pages">';
		echo wp_kses_post(
			paginate_links(
				array(
					'base'      => add_query_arg( AGUD_PAGE_QUERY_ARG, '%#%', menu_page_url( 'auto-generated-urls', false ) ),
					'current'   => $page,
					'total'     => $page_count,
					'type'      => 'list',
					'prev_text' => esc_html__( 'Previous', 'autogenerated-urls' ),
					'next_text' => esc_html__( 'Next', 'autogenerated-urls' ),
				)
			)
		);
		echo '</div></div>';
	}
}

/**
 * Collect paginated author archive URLs.
 *
 * @param int $page  Current page.
 * @param int $total Total matching authors, passed by reference.
 * @return array Labels mapped to author archive URLs.
 */
function agud_get_author_urls( int $page = 1, int &$total = 0 ): array {
	$urls    = array();
	$query   = new WP_User_Query(
		array(
			'capability'  => 'edit_posts',
			'number'      => AGUD_ITEMS_PER_PAGE,
			'offset'      => ( max( 1, $page ) - 1 ) * AGUD_ITEMS_PER_PAGE,
			'count_total' => true,
		)
	);
	$authors = $query->get_results();
	$total   = (int) $query->get_total();
	foreach ( $authors as $author ) {
		/* translators: 1: Author display name. 2: Author ID. */
		$urls[ sprintf( esc_html__( '%1$s (#%2$d)', 'autogenerated-urls' ), $author->display_name, (int) $author->ID ) ] = get_author_posts_url( $author->ID );
	}
	return $urls;
}

/**
 * Collect paginated media attachment URLs.
 *
 * @param int $page  Current page.
 * @param int $total Total matching attachments, passed by reference.
 * @return array Labels mapped to attachment URLs.
 */
function agud_get_attachment_urls( int $page = 1, int &$total = 0 ): array {
	$urls = array();

	$attachment_ids = get_posts(
		array(
			'post_type'      => 'attachment',
			'post_status'    => 'inherit',
			'posts_per_page' => AGUD_ITEMS_PER_PAGE,
			'paged'          => max( 1, $page ),
			'orderby'        => 'ID',
			'order'          => 'ASC',
			'fields'         => 'ids',
		)
	);

	$attachment_counts = wp_count_posts( 'attachment' );
	$total             = isset( $attachment_counts->inherit ) ? (int) $attachment_counts->inherit : 0;

	foreach ( $attachment_ids as $attachment_id ) {
		$attachment_id = (int) $attachment_id;
		$title         = get_the_title( $attachment_id );
		$link          = get_attachment_link( $attachment_id );
		if ( is_string( $link ) && '' !== $link ) {
			/* translators: 1: Attachment title. 2: Attachment ID. */
			$urls[ sprintf( esc_html__( '%1$s (#%2$d)', 'autogenerated-urls' ), $title, $attachment_id ) ] = $link;
		}
	}

	return $urls;
}

/**
 * Collect paginated taxonomy archive URLs.
 *
 * @param string $taxonomy Taxonomy name.
 * @param int    $page     Current page.
 * @param int    $total    Total matching terms, passed by reference.
 * @return array Labels mapped to term archive URLs.
 */
function agud_get_taxonomy_urls( string $taxonomy, int $page = 1, int &$total = 0 ): array {
	$urls = array();

	$terms = get_terms(
		array(
			'taxonomy'   => $taxonomy,
			'hide_empty' => true,
			'number'     => AGUD_ITEMS_PER_PAGE,
			'offset'     => ( max( 1, $page ) - 1 ) * AGUD_ITEMS_PER_PAGE,
		)
	);
	if ( is_wp_error( $terms ) ) {
		$terms = array();
	}
	$term_count = wp_count_terms(
		array(
			'taxonomy'   => $taxonomy,
			'hide_empty' => true,
		)
	);
	$total      = is_wp_error( $term_count ) ? 0 : (int) $term_count;

	$label = 'category' === $taxonomy ? __( 'Category', 'autogenerated-urls' ) : __( 'Tag', 'autogenerated-urls' );
	foreach ( $terms as $term ) {
		$link = get_term_link( $term );
		if ( ! is_wp_error( $link ) && is_string( $link ) && '' !== $link ) {
			/* translators: 1: Taxonomy label. 2: Term name. 3: Term ID. */
			$urls[ sprintf( esc_html__( '%1$s: %2$s (%3$d)', 'autogenerated-urls' ), $label, $term->name, (int) $term->term_id ) ] = $link;
		}
	}

	return $urls;
}

/**
 * Collect the first page of taxonomy and date archive URLs.
 *
 * @return array Labels mapped to archive URLs.
 */
function agud_get_archive_urls(): array {
	$urls           = array();
	$category_total = 0;
	$tag_total      = 0;

	$urls += agud_get_taxonomy_urls( 'category', 1, $category_total );
	$urls += agud_get_taxonomy_urls( 'post_tag', 1, $tag_total );
	$urls += agud_get_date_archive_urls();

	return $urls;
}

/**
 * Collect published year and month archive URLs.
 *
 * @return array Labels mapped to date archive URLs.
 */
function agud_get_date_archive_urls(): array {
	$urls = array();

	global $wpdb;

	// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- A single grouped read avoids the previous N+1 archive queries; results are request-local.
	$pairs = $wpdb->get_results(
		"SELECT DISTINCT YEAR(post_date) AS year_num, MONTH(post_date) AS month_num
    FROM {$wpdb->posts}
    WHERE post_type = 'post' AND post_status = 'publish'
    ORDER BY year_num DESC, month_num DESC"
	);

	$seen_years = array();
	foreach ( $pairs as $pair ) {
		$year  = (int) $pair->year_num;
		$month = (int) $pair->month_num;

		if ( ! isset( $seen_years[ $year ] ) ) {
			/* translators: %d: Four-digit archive year. */
			$urls[ sprintf( esc_html__( 'Year: %d', 'autogenerated-urls' ), $year ) ] = get_year_link( $year );
			$seen_years[ $year ] = true;
		}

		if ( $month > 0 && $month <= 12 ) {
			$month_name = wp_date( 'F', mktime( 0, 0, 0, $month, 1, $year ) );
			/* translators: 1: Month name. 2: Four-digit archive year. */
			$urls[ sprintf( esc_html__( 'Month: %1$s %2$d', 'autogenerated-urls' ), $month_name, $year ) ] = get_month_link( $year, $month );
		}
	}

	return $urls;
}

/**
 * Collect archive URLs for public custom post types.
 *
 * @return array Labels mapped to custom post type archive URLs.
 */
function agud_get_cpt_archive_urls(): array {
	$urls       = array();
	$post_types = get_post_types(
		array(
			'public'      => true,
			'has_archive' => true,
		),
		'objects'
	);
	foreach ( $post_types as $pt ) {
		if ( in_array( $pt->name, array( 'post', 'page' ), true ) ) {
			continue;
		}

		$link = get_post_type_archive_link( $pt->name );
		if ( is_string( $link ) && '' !== $link ) {
			/* translators: 1: Post type label. 2: Post type name. */
			$urls[ sprintf( esc_html__( 'CPT Archive: %1$s (%2$s)', 'autogenerated-urls' ), $pt->labels->name, $pt->name ) ] = $link;
		}
	}

	return $urls;
}
