<?php
/*
Plugin Name: Auto-Generated URLs Display
Description: Finds and displays auto-generated URLs like author archives, 404, search, feeds, REST API, trackbacks, media, archives, and CPT archives.
Version: 1.2
Author: Justin Thompson
Author URI: https://justy.dev
Text Domain: autogenerated-urls
*/

define('AGUD_TEXT_DOMAIN', 'autogenerated-urls');
define('AGUD_ITEMS_PER_PAGE', 100);
define('AGUD_PAGE_QUERY_ARG', 'agud_page');

add_action('plugins_loaded', function () {
  load_plugin_textdomain(AGUD_TEXT_DOMAIN, false, dirname(plugin_basename(__FILE__)) . '/languages');
});

add_action('admin_menu', function () {
  add_management_page(
    __('Auto-Generated URLs', AGUD_TEXT_DOMAIN),
    __('Auto URLs', AGUD_TEXT_DOMAIN),
    'manage_options',
    'auto-generated-urls',
    'agud_display_page'
  );
});

function agud_display_page()
{
  $page = agud_get_current_page();
  $total = 0;

  echo '<div class="wrap"><h1>' . esc_html__('Auto-Generated URLs', AGUD_TEXT_DOMAIN) . '</h1>';

  agud_section(__('Author Archives', AGUD_TEXT_DOMAIN), agud_get_author_urls($page, $total), $total, $page);
  agud_section(__('Static Pages', AGUD_TEXT_DOMAIN), [
    __('404 Example', AGUD_TEXT_DOMAIN) => home_url('/this-path-should-404/'),
    __('Search Page', AGUD_TEXT_DOMAIN) => home_url('/?s=')
  ]);
  agud_section(__('Media Attachments', AGUD_TEXT_DOMAIN), agud_get_attachment_urls($page, $total), $total, $page);
  agud_section(__('Category Archives', AGUD_TEXT_DOMAIN), agud_get_taxonomy_urls('category', $page, $total), $total, $page);
  agud_section(__('Tag Archives', AGUD_TEXT_DOMAIN), agud_get_taxonomy_urls('post_tag', $page, $total), $total, $page);
  agud_section(__('Date Archives', AGUD_TEXT_DOMAIN), agud_get_date_archive_urls());
  agud_section(__('Feed Endpoints', AGUD_TEXT_DOMAIN), [
    __('Main Feed', AGUD_TEXT_DOMAIN)     => home_url('/feed/'),
    __('Comments Feed', AGUD_TEXT_DOMAIN) => home_url('/comments/feed/')
  ]);
  agud_section(__('REST API', AGUD_TEXT_DOMAIN), [
    __('REST API Root', AGUD_TEXT_DOMAIN) => rest_url()
  ]);
  agud_section(__('Pingback URL', AGUD_TEXT_DOMAIN), [
    __('Pingback URL', AGUD_TEXT_DOMAIN) => get_bloginfo('pingback_url')
  ]);
  agud_section(__('Custom Post Type Archives', AGUD_TEXT_DOMAIN), agud_get_cpt_archive_urls());
  agud_section(__('Sitemap', AGUD_TEXT_DOMAIN), [
    __('XML Sitemap', AGUD_TEXT_DOMAIN) => home_url('/wp-sitemap.xml')
  ]);

  echo '</div>';
}

function agud_get_current_page()
{
  $raw_page = $_GET[AGUD_PAGE_QUERY_ARG] ?? 1;
  $page = is_scalar($raw_page) ? absint(wp_unslash($raw_page)) : 1;

  return max(1, $page);
}

function agud_section($title, $urls, $total = 0, $page = 1)
{
  echo '<h2>' . esc_html($title) . '</h2>';
  if (empty($urls)) {
    echo '<p>' . esc_html__('None found.', AGUD_TEXT_DOMAIN) . '</p>';
    return;
  }
  echo '<ul>';
  foreach ($urls as $name => $url) {
    if (!is_string($url) || $url === '') {
      continue;
    }
    echo '<li><strong>' . esc_html($name) . ':</strong> <a href="' . esc_url($url) . '" target="_blank" rel="noopener noreferrer">' . esc_html($url) . '</a></li>';
  }
  echo '</ul>';

  $page_count = (int) ceil($total / AGUD_ITEMS_PER_PAGE);
  if ($page_count > 1) {
    echo '<div class="tablenav"><div class="tablenav-pages">';
    echo wp_kses_post(paginate_links([
      'base'      => add_query_arg(AGUD_PAGE_QUERY_ARG, '%#%', menu_page_url('auto-generated-urls', false)),
      'current'   => $page,
      'total'     => $page_count,
      'type'      => 'list',
      'prev_text' => esc_html__('Previous', AGUD_TEXT_DOMAIN),
      'next_text' => esc_html__('Next', AGUD_TEXT_DOMAIN),
    ]));
    echo '</div></div>';
  }
}

function agud_get_author_urls($page = 1, &$total = 0)
{
  $urls = [];
  $query = new WP_User_Query([
    'who'         => 'authors',
    'number'      => AGUD_ITEMS_PER_PAGE,
    'offset'      => (max(1, $page) - 1) * AGUD_ITEMS_PER_PAGE,
    'count_total' => true,
  ]);
  $authors = $query->get_results();
  $total = (int) $query->get_total();
  foreach ($authors as $author) {
    $urls[sprintf(esc_html__('%1$s (#%2$d)', AGUD_TEXT_DOMAIN), $author->display_name, (int) $author->ID)] = get_author_posts_url($author->ID);
  }
  return $urls;
}

function agud_get_attachment_urls($page = 1, &$total = 0)
{
  $urls = [];

  $attachment_ids = get_posts([
    'post_type'      => 'attachment',
    'post_status'    => 'inherit',
    'posts_per_page' => AGUD_ITEMS_PER_PAGE,
    'paged'          => max(1, $page),
    'orderby'        => 'ID',
    'order'          => 'ASC',
    'fields'         => 'ids',
  ]);

  $attachment_counts = wp_count_posts('attachment');
  $total = isset($attachment_counts->inherit) ? (int) $attachment_counts->inherit : 0;

  foreach ($attachment_ids as $attachment_id) {
    $attachment_id = (int) $attachment_id;
    $title = get_the_title($attachment_id);
    $link = get_attachment_link($attachment_id);
    if (is_string($link) && $link !== '') {
      $urls[sprintf(esc_html__('%1$s (#%2$d)', AGUD_TEXT_DOMAIN), $title, $attachment_id)] = $link;
    }
  }

  return $urls;
}

function agud_get_taxonomy_urls($taxonomy, $page = 1, &$total = 0)
{
  $urls = [];

  $terms = get_terms([
    'taxonomy'   => $taxonomy,
    'hide_empty' => true,
    'number'     => AGUD_ITEMS_PER_PAGE,
    'offset'     => (max(1, $page) - 1) * AGUD_ITEMS_PER_PAGE,
  ]);
  if (is_wp_error($terms)) {
    $terms = [];
  }
  $term_count = wp_count_terms($taxonomy, ['hide_empty' => true]);
  $total = is_wp_error($term_count) ? 0 : (int) $term_count;

  $label = 'category' === $taxonomy ? __('Category', AGUD_TEXT_DOMAIN) : __('Tag', AGUD_TEXT_DOMAIN);
  foreach ($terms as $term) {
    $link = get_term_link($term);
    if (!is_wp_error($link) && is_string($link) && $link !== '') {
      $urls[sprintf(esc_html__('%1$s: %2$s (%3$d)', AGUD_TEXT_DOMAIN), $label, $term->name, (int) $term->term_id)] = $link;
    }
  }

  return $urls;
}

function agud_get_archive_urls()
{
  $urls = [];
  $category_total = 0;
  $tag_total = 0;

  $urls += agud_get_taxonomy_urls('category', 1, $category_total);
  $urls += agud_get_taxonomy_urls('post_tag', 1, $tag_total);
  $urls += agud_get_date_archive_urls();

  return $urls;
}

function agud_get_date_archive_urls()
{
  $urls = [];

  global $wpdb;

  $pairs = $wpdb->get_results(
    "SELECT DISTINCT YEAR(post_date) AS year_num, MONTH(post_date) AS month_num
    FROM {$wpdb->posts}
    WHERE post_type = 'post' AND post_status = 'publish'
    ORDER BY year_num DESC, month_num DESC"
  );

  $seen_years = [];
  foreach ($pairs as $pair) {
    $year = (int) $pair->year_num;
    $month = (int) $pair->month_num;

    if (!isset($seen_years[$year])) {
      $urls[sprintf(esc_html__('Year: %d', AGUD_TEXT_DOMAIN), $year)] = get_year_link($year);
      $seen_years[$year] = true;
    }

    if ($month > 0 && $month <= 12) {
      $month_name = wp_date('F', mktime(0, 0, 0, $month, 1, $year));
      $urls[sprintf(esc_html__('Month: %1$s %2$d', AGUD_TEXT_DOMAIN), $month_name, $year)] = get_month_link($year, $month);
    }
  }

  return $urls;
}

function agud_get_cpt_archive_urls()
{
  $urls = [];
  $post_types = get_post_types(['public' => true, 'has_archive' => true], 'objects');
  foreach ($post_types as $pt) {
    if (in_array($pt->name, ['post', 'page'], true)) {
      continue;
    }

    $link = get_post_type_archive_link($pt->name);
    if (is_string($link) && $link !== '') {
      $urls[sprintf(esc_html__('CPT Archive: %1$s (%2$s)', AGUD_TEXT_DOMAIN), $pt->labels->name, $pt->name)] = $link;
    }
  }

  return $urls;
}
