<?php
/*
Plugin Name: Auto-Generated URLs Display
Description: Finds and displays auto-generated URLs like author archives, 404, search, feeds, REST API, trackbacks, media, archives, and CPT archives.
Version: 1.0
Author: Justin Thompson
Author URI: https://justy.dev
Text Domain: autogenerated-urls
*/

define('AGUD_TEXT_DOMAIN', 'autogenerated-urls');

add_action('plugins_loaded', function () {
  load_plugin_textdomain(AGUD_TEXT_DOMAIN, false, dirname(plugin_basename(__FILE__)) . '/languages');
});

add_action('admin_menu', function () {
  add_management_page(
    __('Auto-Generated URLs', AGUD_TEXT_DOMAIN),
    __('Auto URLs', AGUD_TEXT_DOMAIN),
    'manage_options',
    'auto-generated-urls',
    'agud_display_page'
  );
});

function agud_display_page()
{
  echo '<div class="wrap"><h1>' . esc_html__('Auto-Generated URLs', AGUD_TEXT_DOMAIN) . '</h1>';

  agud_section(__('Author Archives', AGUD_TEXT_DOMAIN), agud_get_author_urls());
  agud_section(__('Static Pages', AGUD_TEXT_DOMAIN), [
    __('404 Example', AGUD_TEXT_DOMAIN) => home_url('/this-path-should-404/'),
    __('Search Page', AGUD_TEXT_DOMAIN) => home_url('/?s=')
  ]);
  agud_section(__('Media Attachments', AGUD_TEXT_DOMAIN), agud_get_attachment_urls());
  agud_section(__('Archive Pages', AGUD_TEXT_DOMAIN), agud_get_archive_urls());
  agud_section(__('Feed Endpoints', AGUD_TEXT_DOMAIN), [
    __('Main Feed', AGUD_TEXT_DOMAIN)     => home_url('/feed/'),
    __('Comments Feed', AGUD_TEXT_DOMAIN) => home_url('/comments/feed/')
  ]);
  agud_section(__('REST API', AGUD_TEXT_DOMAIN), [
    __('REST API Root', AGUD_TEXT_DOMAIN) => rest_url()
  ]);
  agud_section(__('Pingback URL', AGUD_TEXT_DOMAIN), [
    __('Pingback URL', AGUD_TEXT_DOMAIN) => get_bloginfo('pingback_url')
  ]);
  agud_section(__('Custom Post Type Archives', AGUD_TEXT_DOMAIN), agud_get_cpt_archive_urls());
  agud_section(__('Sitemap', AGUD_TEXT_DOMAIN), [
    __('XML Sitemap', AGUD_TEXT_DOMAIN) => home_url('/wp-sitemap.xml')
  ]);

  echo '</div>';
}

function agud_section($title, $urls)
{
  echo '<h2>' . esc_html($title) . '</h2>';
  if (empty($urls)) {
    echo '<p>' . esc_html__('None found.', AGUD_TEXT_DOMAIN) . '</p>';
    return;
  }
  echo '<ul>';
  foreach ($urls as $name => $url) {
    if (!is_string($url) || $url === '') {
      continue;
    }
    echo '<li><strong>' . esc_html($name) . ':</strong> <a href="' . esc_url($url) . '" target="_blank" rel="noopener noreferrer">' . esc_html($url) . '</a></li>';
  }
  echo '</ul>';
}

function agud_get_author_urls()
{
  $urls = [];
  $authors = get_users(['who' => 'authors']);
  foreach ($authors as $author) {
    $urls[sprintf(esc_html__('%1$s (#%2$d)', AGUD_TEXT_DOMAIN), $author->display_name, (int) $author->ID)] = get_author_posts_url($author->ID);
  }
  return $urls;
}

function agud_get_attachment_urls()
{
  $urls = [];

  $page = 1;
  $per_page = 200;

  do {
    $attachment_ids = get_posts([
      'post_type'      => 'attachment',
      'post_status'    => 'inherit',
      'posts_per_page' => $per_page,
      'paged'          => $page,
      'orderby'        => 'ID',
      'order'          => 'ASC',
      'fields'         => 'ids',
    ]);

    foreach ($attachment_ids as $attachment_id) {
      $attachment_id = (int) $attachment_id;
      $title = get_the_title($attachment_id);
      $link = get_attachment_link($attachment_id);
      if (is_string($link) && $link !== '') {
        $urls[sprintf(esc_html__('%1$s (#%2$d)', AGUD_TEXT_DOMAIN), $title, $attachment_id)] = $link;
      }
    }

    $page++;
  } while (!empty($attachment_ids));

  return $urls;
}

function agud_get_archive_urls()
{
  $urls = [];
  $categories = get_categories();
  foreach ($categories as $cat) {
    $link = get_category_link($cat->term_id);
    if (!is_wp_error($link) && is_string($link) && $link !== '') {
      $urls[sprintf(esc_html__('Category: %1$s (%2$d)', AGUD_TEXT_DOMAIN), $cat->name, (int) $cat->term_id)] = $link;
    }
  }

  $tags = get_tags();
  foreach ($tags as $tag) {
    $link = get_tag_link($tag->term_id);
    if (!is_wp_error($link) && is_string($link) && $link !== '') {
      $urls[sprintf(esc_html__('Tag: %1$s (%2$d)', AGUD_TEXT_DOMAIN), $tag->name, (int) $tag->term_id)] = $link;
    }
  }

  global $wpdb;

  $pairs = $wpdb->get_results(
    "SELECT DISTINCT YEAR(post_date) AS year_num, MONTH(post_date) AS month_num
    FROM {$wpdb->posts}
    WHERE post_type = 'post' AND post_status = 'publish'
    ORDER BY post_date DESC"
  );

  $seen_years = [];
  foreach ($pairs as $pair) {
    $year = (int) $pair->year_num;
    $month = (int) $pair->month_num;

    if (!isset($seen_years[$year])) {
      $urls[sprintf(esc_html__('Year: %d', AGUD_TEXT_DOMAIN), $year)] = get_year_link($year);
      $seen_years[$year] = true;
    }

    if ($month > 0 && $month <= 12) {
      $month_name = wp_date('F', mktime(0, 0, 0, $month, 1, $year));
      $urls[sprintf(esc_html__('Month: %1$s %2$d', AGUD_TEXT_DOMAIN), $month_name, $year)] = get_month_link($year, $month);
    }
  }

  return $urls;
}

function agud_get_cpt_archive_urls()
{
  $urls = [];
  $post_types = get_post_types(['public' => true, 'has_archive' => true], 'objects');
  foreach ($post_types as $pt) {
    if (in_array($pt->name, ['post', 'page'], true)) {
      continue;
    }

    $link = get_post_type_archive_link($pt->name);
    if (is_string($link) && $link !== '') {
      $urls[sprintf(esc_html__('CPT Archive: %1$s (%2$s)', AGUD_TEXT_DOMAIN), $pt->labels->name, $pt->name)] = $link;
    }
  }

  return $urls;
}
