<?php

class Test_Autogenerated_URLs extends WP_UnitTestCase
{
  public function test_author_urls_include_created_author()
  {
    $author_id = self::factory()->user->create([
      'role' => 'author',
      'display_name' => 'Review Author',
    ]);

    $urls = agud_get_author_urls();

    $expected_key = sprintf('%1$s (#%2$d)', 'Review Author', $author_id);
    $this->assertArrayHasKey($expected_key, $urls);
    $this->assertSame(get_author_posts_url($author_id), $urls[$expected_key]);
  }

  public function test_archive_urls_include_category_and_tag_entries()
  {
    $category_id = self::factory()->category->create([
      'name' => 'Review Category',
    ]);

    $tag_id = self::factory()->term->create([
      'taxonomy' => 'post_tag',
      'name' => 'Review Tag',
    ]);

    self::factory()->post->create([
      'post_status' => 'publish',
      'post_date' => '2024-03-15 10:00:00',
      'post_category' => [$category_id],
      'tags_input' => ['Review Tag'],
    ]);

    $category_total = 0;
    $tag_total = 0;
    $urls = agud_get_taxonomy_urls('category', 1, $category_total);
    $urls += agud_get_taxonomy_urls('post_tag', 1, $tag_total);

    $category_key = sprintf('Category: %1$s (%2$d)', 'Review Category', $category_id);
    $tag_key = sprintf('Tag: %1$s (%2$d)', 'Review Tag', $tag_id);

    $this->assertArrayHasKey($category_key, $urls);
    $this->assertArrayHasKey($tag_key, $urls);
  }

  public function test_rendered_section_uses_noopener_noreferrer()
  {
    ob_start();
    agud_section('Test', ['Example' => home_url('/')]);
    $output = ob_get_clean();

    $this->assertStringContainsString('rel="noopener noreferrer"', $output);
  }

  public function test_author_urls_paginate_at_one_hundred_items()
  {
    $existing_total = 0;
    agud_get_author_urls(1, $existing_total);
    $this->assertLessThan(101, $existing_total);
    self::factory()->user->create_many(101 - $existing_total, [
      'role' => 'author',
    ]);

    $total = 0;
    $first_page = agud_get_author_urls(1, $total);
    $second_page = agud_get_author_urls(2, $total);

    $this->assertCount(100, $first_page);
    $this->assertCount(1, $second_page);
    $this->assertSame(101, $total);
    $this->assertSame([], array_intersect_key($first_page, $second_page));
  }

  public function test_attachment_urls_paginate_at_one_hundred_items()
  {
    self::factory()->post->create_many(101, [
      'post_type' => 'attachment',
      'post_status' => 'inherit',
    ]);

    $total = 0;
    $first_page = agud_get_attachment_urls(1, $total);
    $second_page = agud_get_attachment_urls(2, $total);

    $this->assertCount(100, $first_page);
    $this->assertCount(1, $second_page);
    $this->assertSame(101, $total);
    $this->assertSame([], array_intersect_key($first_page, $second_page));
  }

  public function test_taxonomy_urls_paginate_at_one_hundred_items()
  {
    $category_ids = self::factory()->term->create_many(101, [
      'taxonomy' => 'category',
    ]);
    $tag_ids = self::factory()->term->create_many(101, [
      'taxonomy' => 'post_tag',
    ]);
    $post_id = self::factory()->post->create([
      'post_status' => 'publish',
    ]);
    wp_set_object_terms($post_id, $category_ids, 'category');
    wp_set_object_terms($post_id, $tag_ids, 'post_tag');

    $category_total = 0;
    $first_category_page = agud_get_taxonomy_urls('category', 1, $category_total);
    $second_category_page = agud_get_taxonomy_urls('category', 2, $category_total);
    $tag_total = 0;
    $first_tag_page = agud_get_taxonomy_urls('post_tag', 1, $tag_total);
    $second_tag_page = agud_get_taxonomy_urls('post_tag', 2, $tag_total);

    $this->assertCount(100, $first_category_page);
    $this->assertCount(1, $second_category_page);
    $this->assertSame(101, $category_total);
    $this->assertSame([], array_intersect_key($first_category_page, $second_category_page));
    $this->assertCount(100, $first_tag_page);
    $this->assertCount(1, $second_tag_page);
    $this->assertSame(101, $tag_total);
    $this->assertSame([], array_intersect_key($first_tag_page, $second_tag_page));
  }
}
