<?php

class Test_Autogenerated_URLs extends WP_UnitTestCase
{
  public function test_author_urls_include_created_author()
  {
    $author_id = self::factory()->user->create([
      'role' => 'author',
      'display_name' => 'Review Author',
    ]);

    $urls = agud_get_author_urls();

    $expected_key = sprintf(esc_html__('%1$s (#%2$d)', AGUD_TEXT_DOMAIN), 'Review Author', $author_id);
    $this->assertArrayHasKey($expected_key, $urls);
    $this->assertSame(get_author_posts_url($author_id), $urls[$expected_key]);
  }

  public function test_archive_urls_include_category_and_tag_entries()
  {
    $category_id = self::factory()->category->create([
      'name' => 'Review Category',
    ]);

    $tag_id = self::factory()->term->create([
      'taxonomy' => 'post_tag',
      'name' => 'Review Tag',
    ]);

    self::factory()->post->create([
      'post_status' => 'publish',
      'post_date' => '2024-03-15 10:00:00',
      'post_category' => [$category_id],
      'tags_input' => ['Review Tag'],
    ]);

    $urls = agud_get_archive_urls();

    $category_key = sprintf(esc_html__('Category: %1$s (%2$d)', AGUD_TEXT_DOMAIN), 'Review Category', $category_id);
    $tag_key = sprintf(esc_html__('Tag: %1$s (%2$d)', AGUD_TEXT_DOMAIN), 'Review Tag', $tag_id);

    $this->assertArrayHasKey($category_key, $urls);
    $this->assertArrayHasKey($tag_key, $urls);
  }

  public function test_rendered_section_uses_noopener_noreferrer()
  {
    ob_start();
    agud_section('Test', ['Example' => home_url('/')]);
    $output = ob_get_clean();

    $this->assertStringContainsString('rel="noopener noreferrer"', $output);
  }
}
